### ISSUE TITLE
Uncaught Error: EISDIR, illegal operation on a directory '/home/ysr/.atom/restore-windows/opened'

### ISSUE THREAD

**Issue by yvan-sraka** [norio-nomura/restore-windows#4]
**Atom Version**: 0.188.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [restore-windows](https://github.com/norio-nomura/restore-windows) package, v0.4.0

### Stack Trace

Uncaught Error: EISDIR, illegal operation on a directory '/home/ysr/.atom/restore-windows/opened'

```
At fs.js:900

Error: EISDIR, illegal operation on a directory '/home/ysr/.atom/restore-windows/opened'
  at Error (native)
  at Object.fs.unlinkSync (fs.js:900:18)
  at Object.module.exports.removeFromOpened (/home/ysr/.atom/packages/restore-windows/lib/restore-windows.coffee:56:8)
  at Object.module.exports.projectPathsChanged (/home/ysr/.atom/packages/restore-windows/lib/restore-windows.coffee:40:6)
  at /home/ysr/.atom/packages/restore-windows/lib/restore-windows.coffee:21:39
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/usr/share/atom/resources/app/src/project.js:302:29)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:39:32)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoclose-html",
      "language-coffee-script",
      "language-python-django-templates",
      "autocomplete-plus",
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
file-icons, v1.5.2
html-entities, v0.3.1
language-latex, v0.4.1
linter, v0.12.0
linter-bootlint, v0.0.4
linter-clang, v2.25.1
linter-clojure, v0.0.4
linter-codscriptizer, v0.2.0
linter-coffeelint, v0.2.0
linter-csslint, v0.0.11
linter-dartanalyzer, v0.3.1
linter-elixirc, v0.2.1
linter-erlc, v0.2.0
linter-flexpmd, v0.1.9
linter-harbour, v1.6.0
linter-hlint, v0.3.1
linter-htmlhint, v0.0.10
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-jsxhint, v0.1.1
linter-less, v0.3.1
linter-lsc, v1.1.2
linter-lua, v0.1.5
linter-php, v0.0.12
linter-puppet-lint, v0.2.8
linter-pyflakes, v0.0.4
linter-pylint, v0.2.1
linter-rubocop, v0.2.2
linter-rust, v0.0.8
linter-scalac, v0.3.3
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
linter-squirrel, v0.3.0
linter-tslint, v0.2.1
linter-xmllint, v0.0.5
minimap, v4.7.0
project-manager, v1.15.5
restore-windows, v0.4.0
tabs-to-spaces, v0.9.2
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by norio-nomura** [comment]
@yvan-sraka Thanks for reporting. I believe this issue has been fixed.
